feat: :heavy_plus_sign: install and test tailwind
MihlaliMgwebi/GithubByMish pull request #1
Opened 2023-03-08 14:14 UTC by MihlaliMgwebi

I set up my directory structure, installed tailwind and tested my installation.

After request for changes or approval, I will build my first component.

2023-03-08 20:57 UTC, kphutiyagae requested changes

2023-03-08 20:57 UTC, kphutiyagae commented on github-by-mish/package.json
> +    "autoprefixer": "^10.4.13",
Is autoprefixer necessary?

2023-03-08 20:57 UTC, kphutiyagae commented on github-by-mish/package.json
> +    "autoprefixer": "^10.4.13",
and postcss?

2023-03-09 11:57 UTC, MihlaliMgwebi commented on github-by-mish/package.json
> +    "autoprefixer": "^10.4.13",
Not at all. I have removed them and pushed my changes. 

Please review again. Thank you for the comment

2023-03-10 10:42 UTC, kphutiyagae commented on github-by-mish/package.json
> +    "autoprefixer": "^10.4.13",
Noted

2023-03-10 10:43 UTC, kphutiyagae approved these changes
Looks good, proceed to merge!

2023-03-10 12:52 UTC, merged